config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get 'posts/index'

  get 'posts/new'

  get 'posts/show'

  get 'posts/edit'

  root "posts#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title,presence: true, length: {maximum: 20}
  validates :message,presence: true, length: {maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render "new"
  end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post deleted' }
      format.json { head :no_content }
    end
  end

  private
		def post_params
			params.require(:post).permit(:title,:message, :schedeled_at,:avatar_url)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Tarea 2", root_path, id: "logo"%>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path%></li>
            <li><%= link_to "New Post", posts_new_path%></li>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
        <strong>Oh snap!</strong> <%= pluralize(@post.errors.count, "error") %> have prevented the post from being recorded
      </div>
    </div>
<% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.label :schedeled_at %>
    <%= f.datetime_select :schedeled_at %>
  </p>

  <p>
    <%= f.label :avatar_url %>
    <%= f.text_field :avatar_url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/_formedit.html.erb
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger" role="alert">
          <strong>Oh snap!</strong> <%= pluralize(@post.errors.count, "error") %> have prevented the post from being recorded
          </div>
        </div>
    <% end %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :message %>
  <%= f.text_area :message %>
</p>

<p>
  <%= f.label :avatar_url %>
  <%= f.text_field :avatar_url %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/posts/edit.html.erb
<h1>EDIT POST</h1>

<%= render 'formedit', post: @post %>
<p>
  <%= link_to 'CANCELAR', @post %> - <%=	link_to 'DELETE',@post, method: :delete, data: {
    confirm: "Seguro?"} %>
</p>

app/views/posts/index.html.erb
<h1>Published Posts</h1>
<% @posts.each do |p| %>
    <h3><%=	link_to p.title, p  %></h3>
    <center>
    <img src="<%=p.avatar_url%>" height="200" width="200" align="center">
    </center>
    <p><%=	p.message  %></p>
<% end %>

app/views/posts/new.html.erb
<h1>Nuevo Post</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/posts/show.html.erb
<h1><%=	@post.title %></h1>
<p><%= @post.avatar_url %></p>
<p><%= @post.message %></p>
<p><%= @post.schedeled_at %></p>

<p><%= link_to 'EDIT', edit_post_path(@post) %> - <%=	link_to 'DELETE',@post, method: :delete, data: {
    confirm: "Seguro?"} %></p>